project:
  type: website
  output-dir: docs

website:
  title: "Home"
  favicon: logo.png
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: research/index.qmd
        text: Research
      - href: cv_2.pdf
        text: CV
        target: _blank

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor:
  render-on-save: true
